#!/bin/sh

clock=$(date '+%I')

TERMINAL=st
EDITOR=vim

case "$clock" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

case $BLOCK_BUTTON in
	#1) setsid  -f "$TERMINAL" -e bash -c "cal; read -n1"  ;;
    1) yad-calendar.sh  ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	6) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
icon2=" "
icon2=""
icon2="📅 "
#icon=" "
#icon=""
#date "+$icon %d %b(%a)$icon2%H:%M"
date "+$icon%H:%M"
#ld-exit
