#!/bin/sh

# Status bar module for disk space
# $1 should be drive mountpoint, otherwise assumed /.

TERMINAL=st
EDITOR=vim
location=${1:-/home}

[ -d "$location" ] || exit

case $BLOCK_BUTTON in
	#1) notify-send "💽 Disk space" "$(df -h --output=target,used,size)" ;;
	1) yad-disk-free.sh ;;
	2) notify-send "💽 Disk module" "\- Shows used hard drive space.
- Click to show all disk info." ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case "$location" in
	"/mnt"* ) icon="🏠" ;;
	"/home"* ) icon="💾" ;;
	*) icon="🖥";;
esac

#printf "%s: %s\n" "$icon" "$(df -h "$location" | awk ' /[0-9]/ {print $3 "/" $2}')"
printf "%s %s\n" "$icon$(df -h "$location" | awk ' FNR==2  {print $5 "/" $2}')"
