#!/bin/sh

TERMINAL=st
EDITOR=vim
#BLOCK_BUTTON=$1


case $BLOCK_BUTTON in
	#1) setsid -f "$TERMINAL" -e pulsemixer ;;
	#1) setsid -f "$TERMINAL" -e alsaemixer ;;
	1) yad-exit.sh ;;
	#1) plus ;;
	#3) minus ;;
	#4) pamixer --allow-boost -i 1 ;;
	#5) pamixer --allow-boost -d 1 ;;
	#3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
#- Middle click to mute.
#- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printf "🏁"



