#!/bin/sh

# Module showing network traffic. Shows how much data has been received (RX) or
# transmitted (TX) since the previous time this script ran. So if run every
# second, gives network traffic per second.

TERMINAL=st
EDITOR=vim

ping() {
    setsid -f "$TERMINAL" -e bash -c "ip addr; 
    ping 8.8.8.8; read -n1; pkill ping" 
}
	
#1) setsid -f "$TERMINAL" -e bash -c "ip addr; read -n1" ;;

case $BLOCK_BUTTON in
	1) ping ;;
	3) notify-send "🌐 Network traffic module" "🔻: Traffic received
🔺: Traffic transmitted" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

#printf "🔻%4sB 🔺%4sB\\n" $(numfmt --to=iec $rx $tx)
printf " 🔻%4sB 🔺%4sB\\n" $(numfmt --to=iec $rx $tx)
#printf "  %3sB  %3sB\\n" $(numfmt --to=iec $rx $tx)
